server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${muy.datasource.driver-class-name}
      url: jdbc:mysql://${muy.datasource.host}:${muy.datasource.port}/${muy.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${muy.datasource.username}
      password: ${muy.datasource.password}
  redis:
    host: ${muy.redis.host}
    port: ${muy.redis.port}
    password:  ${muy.redis.password}
    database: ${muy.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.muy.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

canal:
  server: 192.168.197.133:11111
  destination: example

logging:
  level:
    top.javatool.canal.client: warn
    com:
      muy:
        mapper: debug
        service: info
        controller: info

muy:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: qingmuy
    user-ttl: 7200000
    user-token-name: authentication
  alioss:
    endpoint: ${muy.alioss.endpoint}
    access-key-id: ${muy.alioss.access-key-id}
    access-key-secret: ${muy.alioss.access-key-secret}
    bucket-name: ${muy.alioss.bucket-name}
  wechat:
    appid: ${muy.wechat.appid}
    secret: ${muy.wechat.secret}
